FROM node:20-alpine

WORKDIR /app

EXPOSE 5173

RUN apk add --no-cache bash

COPY package.json package-lock.json* ./

RUN rm -rf node_modules package-lock.json && npm install --legacy-peer-deps

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
